apiVersion: v1
kind: Service
metadata:
  name: harpo-backend
  namespace: harp
  labels:
    app: harpo-backend
spec:
  type: LoadBalancer
  selector:
    app: harpo-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000

