apiVersion: v1
kind: Service
metadata:
  name: harp-api
  namespace: webapps
  labels:
    app: harp-api
spec:
  type: LoadBalancer
  selector:
    app: harp-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: harp-ui
  namespace: webapps
  labels:
    app: harp-ui
spec:
  type: LoadBalancer
  selector:
    app: harpo-ui
  ports:
    - name: http
      port: 80
      targetPort: 80

