apiVersion: v1
kind: PersistentVolume
metadata:
  name: harp-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/www/html/harp
    server: mjolnir
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harp-nfs-pvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: harp-nfs-pv